### ISSUE TITLE
Palette exports

### ISSUE THREAD

**Issue by eadmaster** [TheRealFlamepanther/SGB2-Vaporwave#1]
some of the included palettes looks pretty nice, can you add an export in the Gambatte file format for use with emulators?

https://github.com/libretro/gambatte-libretro/issues/2
https://docs.libretro.com/library/gambatte/#custom-palettes-for-game-boy-games

more palette formats here:
https://www.reddit.com/r/RG350/comments/gybcus/gambatte_palettes_for_gb_games/

**Comment by TheRealFlamepanther** [comment]
Thanks for your interest! Anybody can get the RGB values for the palettes using the SGB Settings Editor tool. I'm currently busy with other projects for the foreseeable future, and will leave that work to anyone who cares to do it.

The settings editor is powerful, easy to use, and located here:
https://www.romhacking.net/utilities/1652/
